// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from './client';
import type { GetUserWishlistsData, GetUserWishlistsResponses, PostUserWishlistsData, PostUserWishlistsResponses } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * returns user's wishlists
 */
export const getUserWishlists = <ThrowOnError extends boolean = false>(options?: Options<GetUserWishlistsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserWishlistsResponses, unknown, ThrowOnError>({
        url: '/user/wishlists',
        ...options
    });
};

/**
 * creates wishlist
 */
export const postUserWishlists = <ThrowOnError extends boolean = false>(options: Options<PostUserWishlistsData, ThrowOnError>) => {
    return (options.client ?? client).post<PostUserWishlistsResponses, unknown, ThrowOnError>({
        url: '/user/wishlists',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};
