// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from './client';
import type { PostUserFriendRequestAcceptData, PostUserFriendRequestAcceptResponses, PostUserFriendRequestNewData, PostUserFriendRequestNewResponses, GetUserFriendWishlistItemsData, GetUserFriendWishlistItemsResponses, GetUserFriendWishlistsData, GetUserFriendWishlistsResponses, GetUserFriendsData, GetUserFriendsResponses, GetUserFriendsRequestsIncomingData, GetUserFriendsRequestsIncomingResponses, PostUserWishlistData, PostUserWishlistResponses, GetUserWishlistItemData, GetUserWishlistItemResponses, PostUserWishlistItemData, PostUserWishlistItemResponses, GetUserWishlistItemsData, GetUserWishlistItemsResponses, GetUserWishlistsData, GetUserWishlistsResponses } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * accepts an incoming friend request
 */
export const postUserFriendRequestAccept = <ThrowOnError extends boolean = false>(options: Options<PostUserFriendRequestAcceptData, ThrowOnError>) => {
    return (options.client ?? client).post<PostUserFriendRequestAcceptResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/user/friend/request/accept',
        ...options
    });
};

/**
 * creates a friend request to another user
 */
export const postUserFriendRequestNew = <ThrowOnError extends boolean = false>(options: Options<PostUserFriendRequestNewData, ThrowOnError>) => {
    return (options.client ?? client).post<PostUserFriendRequestNewResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/user/friend/request/new',
        ...options
    });
};

/**
 * returns wishlist items
 */
export const getUserFriendWishlistItems = <ThrowOnError extends boolean = false>(options: Options<GetUserFriendWishlistItemsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserFriendWishlistItemsResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/user/friend/wishlist/items',
        ...options
    });
};

/**
 * returns user's friend wishlists
 */
export const getUserFriendWishlists = <ThrowOnError extends boolean = false>(options: Options<GetUserFriendWishlistsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserFriendWishlistsResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/user/friend/wishlists',
        ...options
    });
};

/**
 * returns user's friends list
 */
export const getUserFriends = <ThrowOnError extends boolean = false>(options?: Options<GetUserFriendsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserFriendsResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/user/friends',
        ...options
    });
};

/**
 * returns user's incoming friends requests
 */
export const getUserFriendsRequestsIncoming = <ThrowOnError extends boolean = false>(options?: Options<GetUserFriendsRequestsIncomingData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserFriendsRequestsIncomingResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/user/friends/requests/incoming',
        ...options
    });
};

/**
 * creates wishlist
 */
export const postUserWishlist = <ThrowOnError extends boolean = false>(options: Options<PostUserWishlistData, ThrowOnError>) => {
    return (options.client ?? client).post<PostUserWishlistResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/user/wishlist',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * returns wishlist item
 */
export const getUserWishlistItem = <ThrowOnError extends boolean = false>(options: Options<GetUserWishlistItemData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserWishlistItemResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/user/wishlist/item',
        ...options
    });
};

/**
 * creates a wishlist item
 */
export const postUserWishlistItem = <ThrowOnError extends boolean = false>(options: Options<PostUserWishlistItemData, ThrowOnError>) => {
    return (options.client ?? client).post<PostUserWishlistItemResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/user/wishlist/item',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * returns wishlist items
 */
export const getUserWishlistItems = <ThrowOnError extends boolean = false>(options: Options<GetUserWishlistItemsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetUserWishlistItemsResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/user/wishlist/items',
        ...options
    });
};

/**
 * returns user's wishlists
 */
export const getUserWishlists = <ThrowOnError extends boolean = false>(options?: Options<GetUserWishlistsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetUserWishlistsResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/user/wishlists',
        ...options
    });
};
