// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, Client, TDataShape } from './client';
import type { PostApiUserFriendRequestData, PostApiUserFriendRequestResponses, PostApiUserFriendRequestAcceptData, PostApiUserFriendRequestAcceptResponses, PostApiUserFriendRequestDenyData, PostApiUserFriendRequestDenyResponses, GetApiUserFriendWishlistItemsData, GetApiUserFriendWishlistItemsResponses, PostApiUserFriendWishlistWishReservationCancelData, PostApiUserFriendWishlistWishReservationCancelResponses, PostApiUserFriendWishlistWishReservationReserveData, PostApiUserFriendWishlistWishReservationReserveResponses, GetApiUserFriendWishlistsData, GetApiUserFriendWishlistsResponses, GetApiUserFriendsData, GetApiUserFriendsResponses, GetApiUserFriendsRequestsIncomingData, GetApiUserFriendsRequestsIncomingResponses, GetApiUserFriendsRequestsIncomingCountData, GetApiUserFriendsRequestsIncomingCountResponses, GetApiUserFriendsRequestsOutcomingData, GetApiUserFriendsRequestsOutcomingResponses, DeleteApiUserWishlistData, DeleteApiUserWishlistResponses, PatchApiUserWishlistData, PatchApiUserWishlistResponses, PostApiUserWishlistData, PostApiUserWishlistResponses, GetApiUserWishlistAccessData, GetApiUserWishlistAccessResponses, GetApiUserWishlistItemData, GetApiUserWishlistItemResponses, PatchApiUserWishlistItemData, PatchApiUserWishlistItemResponses, PostApiUserWishlistItemData, PostApiUserWishlistItemResponses, GetApiUserWishlistItemsData, GetApiUserWishlistItemsResponses, GetApiUserWishlistsData, GetApiUserWishlistsResponses } from './types.gen';
import { client } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * creates a friend request to another user
 */
export const postApiUserFriendRequest = <ThrowOnError extends boolean = false>(options: Options<PostApiUserFriendRequestData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiUserFriendRequestResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/friend/request',
        ...options
    });
};

/**
 * accepts an incoming friend request
 */
export const postApiUserFriendRequestAccept = <ThrowOnError extends boolean = false>(options: Options<PostApiUserFriendRequestAcceptData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiUserFriendRequestAcceptResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/friend/request/accept',
        ...options
    });
};

/**
 * accepts an incoming friend request
 */
export const postApiUserFriendRequestDeny = <ThrowOnError extends boolean = false>(options: Options<PostApiUserFriendRequestDenyData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiUserFriendRequestDenyResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/friend/request/deny',
        ...options
    });
};

/**
 * returns wishlist items
 */
export const getApiUserFriendWishlistItems = <ThrowOnError extends boolean = false>(options: Options<GetApiUserFriendWishlistItemsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiUserFriendWishlistItemsResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/friend/wishlist/items',
        ...options
    });
};

/**
 * reserves friend's wish
 */
export const postApiUserFriendWishlistWishReservationCancel = <ThrowOnError extends boolean = false>(options: Options<PostApiUserFriendWishlistWishReservationCancelData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiUserFriendWishlistWishReservationCancelResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/friend/wishlist/wish/reservation/cancel',
        ...options
    });
};

/**
 * reserves friend's wish
 */
export const postApiUserFriendWishlistWishReservationReserve = <ThrowOnError extends boolean = false>(options: Options<PostApiUserFriendWishlistWishReservationReserveData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiUserFriendWishlistWishReservationReserveResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/friend/wishlist/wish/reservation/reserve',
        ...options
    });
};

/**
 * returns user's friend wishlists
 */
export const getApiUserFriendWishlists = <ThrowOnError extends boolean = false>(options: Options<GetApiUserFriendWishlistsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiUserFriendWishlistsResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/friend/wishlists',
        ...options
    });
};

/**
 * returns user's friends list
 */
export const getApiUserFriends = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserFriendsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiUserFriendsResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/friends',
        ...options
    });
};

/**
 * returns user's incoming friends requests
 */
export const getApiUserFriendsRequestsIncoming = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserFriendsRequestsIncomingData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiUserFriendsRequestsIncomingResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/friends/requests/incoming',
        ...options
    });
};

/**
 * returns user's incoming friends requests count
 */
export const getApiUserFriendsRequestsIncomingCount = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserFriendsRequestsIncomingCountData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiUserFriendsRequestsIncomingCountResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/friends/requests/incoming/count',
        ...options
    });
};

/**
 * returns user's incoming friends requests
 */
export const getApiUserFriendsRequestsOutcoming = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserFriendsRequestsOutcomingData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiUserFriendsRequestsOutcomingResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/friends/requests/outcoming',
        ...options
    });
};

/**
 * creates wishlist
 */
export const deleteApiUserWishlist = <ThrowOnError extends boolean = false>(options: Options<DeleteApiUserWishlistData, ThrowOnError>) => {
    return (options.client ?? client).delete<DeleteApiUserWishlistResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/wishlist',
        ...options
    });
};

/**
 * creates wishlist
 */
export const patchApiUserWishlist = <ThrowOnError extends boolean = false>(options: Options<PatchApiUserWishlistData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchApiUserWishlistResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/wishlist',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * creates wishlist
 */
export const postApiUserWishlist = <ThrowOnError extends boolean = false>(options: Options<PostApiUserWishlistData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiUserWishlistResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/wishlist',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * returns wishlist access list
 */
export const getApiUserWishlistAccess = <ThrowOnError extends boolean = false>(options: Options<GetApiUserWishlistAccessData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiUserWishlistAccessResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/wishlist/access',
        ...options
    });
};

/**
 * returns wishlist item
 */
export const getApiUserWishlistItem = <ThrowOnError extends boolean = false>(options: Options<GetApiUserWishlistItemData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiUserWishlistItemResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/wishlist/item',
        ...options
    });
};

/**
 * updates a wishlist item
 */
export const patchApiUserWishlistItem = <ThrowOnError extends boolean = false>(options: Options<PatchApiUserWishlistItemData, ThrowOnError>) => {
    return (options.client ?? client).patch<PatchApiUserWishlistItemResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/wishlist/item',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * creates a wishlist item
 */
export const postApiUserWishlistItem = <ThrowOnError extends boolean = false>(options: Options<PostApiUserWishlistItemData, ThrowOnError>) => {
    return (options.client ?? client).post<PostApiUserWishlistItemResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/wishlist/item',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * returns wishlist items
 */
export const getApiUserWishlistItems = <ThrowOnError extends boolean = false>(options: Options<GetApiUserWishlistItemsData, ThrowOnError>) => {
    return (options.client ?? client).get<GetApiUserWishlistItemsResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/wishlist/items',
        ...options
    });
};

/**
 * returns user's wishlists
 */
export const getApiUserWishlists = <ThrowOnError extends boolean = false>(options?: Options<GetApiUserWishlistsData, ThrowOnError>) => {
    return (options?.client ?? client).get<GetApiUserWishlistsResponses, unknown, ThrowOnError>({
        security: [
            {
                name: 'Authorization',
                type: 'apiKey'
            }
        ],
        url: '/api/user/wishlists',
        ...options
    });
};
