// This file is auto-generated by @hey-api/openapi-ts

export type ServiceCreateWishlistItemRequest = {
    description?: string;
    links?: Array<ServiceWishlistItemLink>;
    price?: string;
    reservable?: boolean;
    title?: string;
};

export type ServiceCreateWishlistRequest = {
    description?: string;
    is_private?: boolean;
    title?: string;
};

export type ServiceFriend = {
    id?: number;
    photo_url?: string;
    username?: string;
};

export type ServiceWishlist = {
    description?: string;
    id?: number;
    is_private?: boolean;
    title?: string;
};

export type ServiceWishlistItem = {
    description?: string;
    id?: number;
    links?: Array<ServiceWishlistItemLink>;
    price?: string;
    reservable?: boolean;
    reserved_by?: number;
    title?: string;
    wishlist_id?: number;
};

export type ServiceWishlistItemLink = {
    title?: string;
    url?: string;
};

export type GetUserFriendsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/friends';
};

export type GetUserFriendsResponses = {
    /**
     * OK
     */
    200: Array<ServiceFriend>;
};

export type GetUserFriendsResponse = GetUserFriendsResponses[keyof GetUserFriendsResponses];

export type GetUserFriendsRequestsIncomingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/friends/requests/incoming';
};

export type GetUserFriendsRequestsIncomingResponses = {
    /**
     * OK
     */
    200: Array<ServiceFriend>;
};

export type GetUserFriendsRequestsIncomingResponse = GetUserFriendsRequestsIncomingResponses[keyof GetUserFriendsRequestsIncomingResponses];

export type PostUserFriendsRequestsByFriendIdData = {
    body?: never;
    path: {
        /**
         * Friend ID
         */
        friend_id: number;
    };
    query?: never;
    url: '/user/friends/requests/{friend_id}';
};

export type PostUserFriendsRequestsByFriendIdResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostUserFriendsRequestsByFriendIdResponse = PostUserFriendsRequestsByFriendIdResponses[keyof PostUserFriendsRequestsByFriendIdResponses];

export type PostUserFriendsRequestsByFriendIdAcceptData = {
    body?: never;
    path: {
        /**
         * Friend ID
         */
        friend_id: number;
    };
    query?: never;
    url: '/user/friends/requests/{friend_id}/accept';
};

export type PostUserFriendsRequestsByFriendIdAcceptResponses = {
    /**
     * OK
     */
    200: {
        [key: string]: string;
    };
};

export type PostUserFriendsRequestsByFriendIdAcceptResponse = PostUserFriendsRequestsByFriendIdAcceptResponses[keyof PostUserFriendsRequestsByFriendIdAcceptResponses];

export type GetUserWishlistItemData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Wishlist item ID
         */
        item_id: number;
    };
    url: '/user/wishlist/item';
};

export type GetUserWishlistItemResponses = {
    /**
     * OK
     */
    200: ServiceWishlistItem;
};

export type GetUserWishlistItemResponse = GetUserWishlistItemResponses[keyof GetUserWishlistItemResponses];

export type PostUserWishlistItemData = {
    /**
     * request body
     */
    body: ServiceCreateWishlistItemRequest;
    path?: never;
    query: {
        /**
         * Wishlist ID
         */
        wishlist_id: number;
    };
    url: '/user/wishlist/item';
};

export type PostUserWishlistItemResponses = {
    /**
     * OK
     */
    200: ServiceWishlistItem;
};

export type PostUserWishlistItemResponse = PostUserWishlistItemResponses[keyof PostUserWishlistItemResponses];

export type GetUserWishlistItemsData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Wishlist ID
         */
        wishlist_id: number;
    };
    url: '/user/wishlist/items';
};

export type GetUserWishlistItemsResponses = {
    /**
     * OK
     */
    200: Array<ServiceWishlistItem>;
};

export type GetUserWishlistItemsResponse = GetUserWishlistItemsResponses[keyof GetUserWishlistItemsResponses];

export type GetUserWishlistsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/wishlists';
};

export type GetUserWishlistsResponses = {
    /**
     * OK
     */
    200: Array<ServiceWishlist>;
};

export type GetUserWishlistsResponse = GetUserWishlistsResponses[keyof GetUserWishlistsResponses];

export type PostUserWishlistsData = {
    /**
     * request body
     */
    body: ServiceCreateWishlistRequest;
    path?: never;
    query?: never;
    url: '/user/wishlists';
};

export type PostUserWishlistsResponses = {
    /**
     * OK
     */
    200: ServiceWishlist;
};

export type PostUserWishlistsResponse = PostUserWishlistsResponses[keyof PostUserWishlistsResponses];

export type ClientOptions = {
    baseUrl: 'localhost:8080/api' | (string & {});
};
