// This file is auto-generated by @hey-api/openapi-ts

export type ServiceCreateWishlistRequest = {
    description?: string;
    is_private?: boolean;
    title?: string;
};

export type ServiceWishlist = {
    description?: string;
    id?: number;
    is_private?: boolean;
    title?: string;
};

export type GetUserWishlistsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/user/wishlists';
};

export type GetUserWishlistsResponses = {
    /**
     * OK
     */
    200: Array<ServiceWishlist>;
};

export type GetUserWishlistsResponse = GetUserWishlistsResponses[keyof GetUserWishlistsResponses];

export type PostUserWishlistsData = {
    /**
     * request body
     */
    body: ServiceCreateWishlistRequest;
    path?: never;
    query?: never;
    url: '/user/wishlists';
};

export type PostUserWishlistsResponses = {
    /**
     * OK
     */
    200: ServiceWishlist;
};

export type PostUserWishlistsResponse = PostUserWishlistsResponses[keyof PostUserWishlistsResponses];

export type ClientOptions = {
    baseUrl: string;
};
