name: Lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # Checkout the repository
      - name: Install dependencies
        run: npm install # Or yarn install, pnpm install, etc.
      - name: Run ESLint
        run: npx run lint # Adjust extensions as needed